# Generated by Django 3.1.4 on 2021-01-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneverification',
            name='phone',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
